const actionTypes = Object.freeze({
    TEST_START: "TEST_START",
    TEST_SUCCESS: "TEST_SUCCESS",
    TEST_FAILED: "TEST_FAILED",

    TEST_DATA: 'TEST_DATA',
    TEST_SUCCESS_DATA: "TEST_SUCCESS_DATA",

    GET_DATA_FROM_SEARCH_FILM: "GET_DATA_FROM_SEARCH_FILM",
})

export default actionTypes;